language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "snLfKnyKJJHM1t1yfCYnAGys6ts2QUyJm6WeyqDOa5FLEpg0so8vYUj4Rf31WXCrMx9X86Hl4qMChOqvVh4FBF2CISU3mMtcbQH2HZw7Raw7/YYEwBl0NPsdXLNxzBxS46VTZs4tADhJcrQEPzAO3h7TchCrnFu1PYEws5N0/0I7n8RgVRtMmm2AJVHwSMQFusduPL+RPtSrTMfvPbhvgRs4iUQeEJ45ge+2IwsIpfeEUoxGzY3aEKQJGmMKedFY9UbC6a1vobMpgc4ljr+06t3YG/Uz9S5EulWgjxl6S4FkwqPomxwyPwBRuvDxwNPAw/rNf4d/76siLDVLSL4Avth/zDWtOmD0zTzY70d1us7u4XRqReg6bV30dW397pJMRRyI6aSO8ItSt8FLjuFLhi/zR8PTCEL8ZLImvBLIcY1/KJGJFIIIG//olUKNBFCGJ4GThxcwnt8lqFz0Be5E9Jj3zWuSGYeJywGjn2lVcqy64t7qxn2WB7MZdMLnAjYTlOJXCPeHC+ktglNn1VkhzXcOmrmEuOGUCivk3rdT1HzDTAw0v0ka/JtqKgxBdOmfNMFxfEb+62XIH9eFZ/xj2sjZ3dq3FTgSPLYsWZ/K4bv/vwzrGGRNNvZ3DPpPSbUsktRt6m82xnnlG92fwBU0qHeoxeSR/ZiTHjN48J/GtuU="
  api_key: # 9899
    secure: "MyNSdbGU3QG09M/95v9L/jH90AtTMf6qMgxm8fZqM8VJCNo8kZ97v3VpHXdQV93aSXgEghCX02rsZtkmDcj7PLHBr1HSp1EuhLc/bQ+UJHjqvBQs2SInNUnygsuMjUNnm4U4t4lZBU4uUx+fIoYlMOTUvAr9xi33d8jCyC+zZvE9sX/CrYv6viZvcWYxYo8ut6fjsO0tHm2G8QZVfYNjVcY8is+6OhlN42XRPG8+ziDXS7GT7yzy3L9F37rqQhClngcI325mzmosRaHdjppBA1dE3yLBZsvYIWtfpxAKrYmTOxp0oRjZ6DSzyJTW4olhpBcRffWSIwmEghGxt2mnw0aEpapBUv9JJ85oKc41qK8N5WXN/iVCrXPqr7usqOx9mLPbWBgtugp1Rc4cTXJMEtLsqCSJ70cKXtYNj3QlyjY4tegu2wokOaJENkN1U55wqPq5BVdgyJTukbQnEhvjWr3TeF9hmHZi51EEHgsf3Y0wyVe5YWTtypOX1lHz6DKU2+1WIo2ZemoEwfrGwZA32JonYpWTA6vvbNjq3T3+jfn1EEX3P0BziPM12ofXuhzZ8AP8bmy3cmQlwuiSlG5Av492lOt7H8ZNVbiyQpo7BB6GGCtGWi7CqyevI66JVhvq/lO4DmmidiS6DtkJ4stg6lMP1tcMQwy//5B1tZ24BKQ="
  on:
    tags: true
    node: lts/*
